# Site settings
title: zhoulin-cirlce Blog
SEOTitle: circle的博客 |  zhoulin-cirlce Blog
header-img: img/home-bg.jpg
email: zlinjiejie@sina.com
description: "关于前端最新技术 | zhoulin-cirlce，Web & Software Engineer| 这里是 @zhoulin-cirlce 的个人博客，与你一起发现更大的世界。"
keyword: "zhoulin, cirlce, circle, 前端, rocketchat, @zhoulin-cirlce,zhoulin-cirlce Blog, 博客, 个人网站, 互联网, Web, JavaScript, node"
url: "https://zhoulin-cirlce.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
github_username:    zhoulin-cirlce
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，分享生活，<br>你的选择,自己做主"
sidebar-avatar: /img/avatar-circle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

